### ISSUE TITLE
Ability to use dunner with docker images whose entrypoint is defined

### ISSUE THREAD

**Issue by apoorvam** [RSVPLK/Dunner#175]
For Docker images whose entrypoint is defined and are run as an executable, Dunner fails to execute commands defined in it. 

Example: [Goreleaser's docker](https://github.com/goreleaser/goreleaser/blob/master/Dockerfile) file. 

Dunner task file: 

```
tasks:
  release:
    steps:
      - image: goreleaser/goreleaser
        commands:
          - ["echo", "hello"]
          - ["goreleaser", "--version"]
```

Running this command with dunner fails with error as: 

```
OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown
FATA[2019-08-26 18:39:51] docker: command execution failed with exit code 126
```

**Comment by agentmilindu** [comment]
What if the entry point is something like `/app/src/python/main/analyze.py`? Then someone who uses this docker needs to put this again and again in commands, right? 
```
tasks:
  release:
    steps:
      - image: SCoRe/MLKit
        commands:
          - ["/app/src/python/main/analyze.py", "--algo","ImageNet"]
```
